ports:
  - port: 9080 # npmgraph web preview
    visibility: public
tasks:
  - init: npm install && npm install -g static-server
    command: >
      static-server

  - init: npm install -g verdaccio
    command: >
      verdaccio